class Cell {
    + type : CellType <<get>> <<set>>
    + id : string <<get>> <<set>>
    + kind : EnemyKind? <<get>> <<set>> = null
    + currency : int <<get>> <<set>>
    - rect : Rectangle
    - state : State
    + SetData(level:LevelData, columnId:int, rowId:int, fillColumns:int, fillRows:int) : void
    + StartOpening() : void
    + FinishOpening(sender:object, e:EventArgs) : void
    + Reset() : void
    + Update(deltaTime:float) : void
    + Draw() : void
    + DrawAfter() : void
}
IDynamicNode <|-- Cell
Cell --> "transform" Transform
Cell --> "level" LevelData
Cell o-> "animation" PeelingCellAnimation
