class Cell {
    - {static} <<readonly>> dmgFont : Font
    + type : CellType <<get>> <<set>>
    + id : string <<get>> <<set>>
    + kind : EnemyKind? <<get>> <<set>> = null
    + currency : int <<get>> <<set>>
    - state : State
    - dmgAround : int = 0
    - dmgAroundRelative : int = 0
    + Reload() : void
    + SetData(level:LevelData, columnId:int, rowId:int, fillColumns:int, fillRows:int) : void
    + SetEnemy(enemy:Enemy) : void
    + AddDmgAround(dmg:int) : void
    + UpdateDmgAround(dmg:int) : void
    + StartOpening() : void
    + FinishOpening() : void
    + Reset() : void
    + Update(deltaTime:float) : void
    + Draw() : void
    + DrawAfter() : void
}
IDynamicNode <|-- Cell
Cell --> "transform" Transform
Cell --> "level" LevelData
Cell o-> "peelingAnimation" PeelingCellAnimation
Cell o-> "enemy" Enemy
Cell --> "renderer" Renderer
