class EnemyFactory {
    - <<readonly>> EnemyPrototypes : Dictionary<EnemyKind, Enemy>
    - EnemyFactory()
    + {static} Create(x:int, y:int, kind:EnemyKind) : Enemy
    - RecreatePrototypes() : void
}
EnemyFactory o-> "Instance" EnemyFactory
