class EnemyFactory {
    - <<readonly>> EnemyPrototypes : Dictionary<EnemyKind, Enemy>
    + EnemyFactory(bus:EventBus)
    + Create(x:int, y:int, kind:EnemyKind) : Enemy
    - RecreatePrototypes(bus:EventBus) : void
}
