class Enemy {
    - <<readonly>> tile : Image
    + Damage : int <<get>>
    - state : State
    + Enemy(x:int, y:int, kind:EnemyKind)
    + Defeat() : void
    + IsAlive() : bool
    + Reset() : void
    + Clone(x:int, y:int) : Enemy
    + Draw() : void
}
IStaticNode <|-- Enemy
Enemy --> "Transform" Transform
Enemy --> "Collisioner" Collisioner
Enemy --> "renderer" Renderer
