class GameManager {
    - state : GameState
    - <<readonly>> font : Font
    - level : int
    - maxLvls : int
    - GameManager()
    - ReadLevelCount() : void
    + OnPlay() : void
    + OnRetry() : void
    + OnExit() : void
    - HandleLose(data:PlayerDiedEvent) : void
    + HandleVictory(data:LevelWinEvent) : void
    + NextLevel() : void
    + OnMainMenu() : void
    + Input() : void
    + Update(deltaTime:float) : void
    + Draw() : void
}
IDynamicNode <|-- GameManager
GameManager o-> "Instance" GameManager
GameManager --> "levelManager" LevelManager
GameManager --> "defeat" DefeatScreen
GameManager --> "victory" VictoryScreen
GameManager o-> "bus" EventBus
