@startuml
class GameManager {
    - level : int
    - maxLvls : int
    - GameManager()
    - ReadLevelCount() : void
    + OnPlay() : void
    + OnRetry() : void
    + OnExit() : void
    - HandleLose() : void
    + HandleVictory() : void
    + NextLevel() : void
    + OnMainMenu() : void
    + Input() : void
    + Update(deltaTime:float) : void
    + Draw() : void
}
enum GameState {
    MAIN_MENU,
    PLAYING_LEVEL,
    VICTORY,
    DEFEAT,
    QUIT,
}
IDynamicNode <|-- GameManager
GameManager o-> "state" GameState
GameManager o-> "Instance" GameManager
GameManager o-> "font" Font
GameManager o-> "levelManager" LevelManager
GameManager --> "defeat" DefeatScreen
GameManager --> "victory" VictoryScreen
GameManager +-- GameState
@enduml
