class Grid {
    + <<const>> MAX_ROW : int = 16
    + <<const>> MAX_COLUMN : int = 32
    - lvlRows : int
    - lvlColumns : int
    - fillRows : int
    - fillColumns : int
    + GenerateLevel(level:LevelData, enemies:List<Enemy>, player:Player) : void
    + Reset() : void
    + PlayerCanMove(position:Point) : bool
    + CheckIfPlayerWon(player:Player) : void
    + Update(deltaTime:float) : void
    + Draw() : void
    + DrawAfter() : void
}
IDynamicNode <|-- Grid
Grid o-> "bus" EventBus
Grid --> "level" LevelData
