class Grid {
    + <<readonly>> MAX_ROW : int
    + <<readonly>> MAX_COLUMN : int
    - lvlRows : int
    - lvlColumns : int
    - fillRows : int
    - fillColumns : int
    - <<readonly>> emptyCells : List<Renderer>
    + Grid(bus:EventBus)
    - PlayerResetHandler(data:PlayerResetEvent) : void
    - PlayerMoveHandler(data:PlayerMoveEvent) : void
    - EnemyDeadHandler(data:EnemyDeadEvent) : void
    + GenerateLevel(level:LevelData, enemies:List<Enemy>, player:Player) : void
    - GenerateEmptyCells() : void
    + Reset() : void
    + PlayerCanMove(position:Point) : bool
    + CheckIfPlayerWon(player:Player) : void
    + Update(deltaTime:float) : void
    + Draw() : void
    + DrawAfter() : void
}
IDynamicNode <|-- Grid
Grid --> "enemyFactory" EnemyFactory
Grid --> "bus" EventBus
Grid --> "level" LevelData
