@startuml
class Grid {
    - <<readonly>> MAX_ROW : int = 16
    - <<readonly>> MAX_COLUMN : int = 32
    - lvlRow : int
    - lvlColumn : int
    - fillRows : int
    - fillColumns : int
    + SetLevel(level:LevelData) : void
    + Reset() : void
    + Update(deltaTime:float) : void
    + Draw() : void
    + DrawAfter() : void
}
IDynamicNode <|-- Grid
Grid --> "level" LevelData
@enduml
