class LevelWinEvent {
}
class LevelManager {
    - <<readonly>> levels : Dictionary<int, LevelData>
    - {static} <<readonly>> enemies : List<Enemy>
    + {static} ActiveEnemies : List<Enemy> <<get>>
    + LevelManager(font:Font, bus:EventBus)
    - LoadLevel(level:int) : LevelData
    + ResetLevel() : void
    - PlayerWillMoveHandler(data:PlayerMoveEvent) : void
    - RunCollisions() : void
    + StartLevel(level:int) : void
    + <<override>> Input() : void
    + <<override>> Update(deltaTime:float) : void
    + <<override>> Draw() : void
}
Event <|-- LevelWinEvent
InteractiveNode <|-- LevelManager
LevelManager --> "Renderer" Renderer
LevelManager --> "player" Player
LevelManager --> "grid" Grid
LevelManager --> "ui" LevelUI
