@startuml
class LevelManager {
    +  <<event>> OnLose : LevelEventLose 
    +  <<event>> OnWin : LevelEventWin 
    - LevelManager()
    - LoadLevel(level:int) : LevelData
    + ResetLevel() : void
    - PlayerDeathHandler() : void
    - PlayerWillMoveHandler(position:Point) : void
    - RunCollisions() : void
    - CheckVictoryCondition() : void
    + StartLevel(level:int) : void
    + Init(font:Font) : void
    + <<override>> Input() : void
    + <<override>> Update(deltaTime:float) : void
    + <<override>> Draw() : void
}
class "Dictionary`2"<T1,T2> {
}
class "List`1"<T> {
}
InteractiveNode <|-- LevelManager
LevelManager o-> "levels<int,LevelData>" "Dictionary`2"
LevelManager --> "Renderer" Renderer
LevelManager o-> "player" Player
LevelManager o-> "enemies<Enemy>" "List`1"
LevelManager --> "ActiveEnemies<Enemy>" "List`1"
LevelManager o-> "grid" Grid
LevelManager --> "ui" LevelUI
LevelManager o-> "Instance" LevelManager
@enduml
