@startuml
class LevelDataProps {
}
class LevelData {
    + Reset() : void
}
class "List`1"<T> {
}
LevelDataProps --> "start" Color
LevelDataProps --> "end" Color
LevelDataProps --> "basic" Color
LevelDataProps --> "lineMesh" Color
LevelDataProps --> "treasure" Color
LevelDataProps --> "background" Color
LevelData --> "props" LevelDataProps
LevelData --> "grid<List<Cell>>" "List`1"
@enduml
