@startuml
class Player {
    +  <<event>> OnWillMove : PlayerEventWillMove 
    +  <<event>> OnDeath : PlayerEventIsDead 
    - <<readonly>> maxHealth : int = 8
    + Hp : int <<get>>
    + Player(x:int, y:int)
    + SetStart(x:int, y:int) : void
    + Reset() : void
    + TakeDamage(damage:int) : void
    - IsDead() : bool
    + Move(newPosition:Point) : void
    + TryCollide(enemy:Enemy) : bool
    + Input() : void
    + Update(deltaTime:float) : void
    + Draw() : void
}
IInteractiveNode <|-- Player
Player --> "start" Point
Player --> "Tile" Image
Player --> "Collisioner" Collisioner
Player --> "Transform" Transform
@enduml
