class PlayerMoveEvent {
    + <<readonly>> Position : Point
}
class PlayerWantToMoveEvent {
    + <<readonly>> Position : Point
}
class PlayerDmgEvent {
    + <<readonly>> Hp : int
    + <<readonly>> Dmg : int
}
class PlayerResetEvent {
    + <<readonly>> Hp : int
    + <<readonly>> Position : Point
}
class PlayerDiedEvent {
}
class Player {
    - start : Point
    + Tile : Image <<get>>
    - <<readonly>> maxHealth : int = 8
    + Hp : int <<get>>
    + Player(bus:EventBus, x:int, y:int)
    + SetStart(x:int, y:int) : void
    + Reset() : void
    + TakeDamage(damage:int) : void
    - IsDead() : bool
    + Move(newPosition:Point) : void
    + TryCollide(enemy:Enemy) : bool
    + <<override>> Input() : void
    + <<override>> Draw() : void
}
Event <|-- PlayerMoveEvent
Event <|-- PlayerWantToMoveEvent
Event <|-- PlayerDmgEvent
Event <|-- PlayerResetEvent
Event <|-- PlayerDiedEvent
InteractiveNode <|-- Player
Player --> "Collisioner" Collisioner
Player --> "Transform" Transform
Player --> "renderer" Renderer
Player --> "bus" EventBus
