@startuml
class CollisionEvent {
    + <<readonly>> id : string
}
class CollisionManager {
    - CollisionManager()
    + {static} ValidateCollitions() : void
    + <<override>> Draw() : void
}
Node <|-- CollisionManager
CollisionManager o-> "Instance" CollisionManager
@enduml
