@startuml
class Collisioner {
    + UpdatePosition(position:Point) : void
    + Reset(position:Point?) : void
    + CheckCollision(element:Collisioner) : bool
}
Collisioner o-> "rect" Rectangle
Collisioner --> "Rect" Rectangle
@enduml
