class Collisioner {
    - rect : Rectangle
    + UpdatePosition(transform:Transform) : void
    + CheckCollision(element:Collisioner) : bool
}
class ColorJsonConverter {
    + <<override>> Read(reader:Utf8JsonReader, typeToConvert:System.Type, options:JsonSerializerOptions) : Color
    + <<override>> Write(writer:Utf8JsonWriter, value:Color, options:JsonSerializerOptions) : void
}
class "JsonConverter`1"<T> {
}
"JsonConverter`1" "<Color>" <|-- ColorJsonConverter
class Engine <<static>> {
    - {static} <<readonly>> sounds : Dictionary<string, SoundPlayer>
    - {static} <<readonly>> drawQueue : List<IDrawCommand>
    - {static} window : GameForm
    + {static} IsWindowOpen : bool <<get>>
    + {static} Window : Form <<get>>
    - {static} <<readonly>> pressedKeys : HashSet<Keys>
    - {static} <<readonly>> handledKeys : HashSet<Keys>
    - {static} <<readonly>> releasedKeys : HashSet<Keys>
    - {static} <<readonly>> handledReleasedKeys : HashSet<Keys>
    - {static} <<readonly>> debugFont : Font
    - {static} <<readonly>> debugBrush : Brush
    + {static} Initialize(title:string, width:int, height:int, fullscreen:bool) : void
    + {static} UpdateWindow() : void
    + {static} PlaySound(path:string) : void
    + {static} DrawACommand(command:IDrawCommand) : void
    + {static} DrawRect(rect:Rectangle, pen:Pen, brush:Brush) : void
    + {static} DrawText(text:string, font:Font, brush:Brush, position:Point) : void
    + {static} Clear(color:Color) : void
    + {static} OnKeyDown(key:Keys) : bool
    + {static} OnKeyUp(key:Keys) : bool
    + {static} IsKeyDown(key:Keys) : bool
    + {static} IsKeyPressed(key:Keys) : bool
}
class JsonConfiguration <<static>> {
}
JsonConfiguration o-> "Options" JsonSerializerOptions
class PointJsonConverter {
    + <<override>> Read(reader:Utf8JsonReader, typeToConvert:System.Type, options:JsonSerializerOptions) : Point
    + <<override>> Write(writer:Utf8JsonWriter, value:Point, options:JsonSerializerOptions) : void
}
class "JsonConverter`1"<T> {
}
"JsonConverter`1" "<Point>" <|-- PointJsonConverter
class Renderer {
    + Draw() : void
}
Renderer o-> "Command" IDrawCommand
class TileMap {
    + {static} Size : int <<get>> = 32
    + {static} LoadSprite(path:string, column:int, row:int) : Bitmap
    + {static} LoadSprite(path:string, x:int, y:int, size:Size) : Bitmap
}
class Transform {
    + {static} <<readonly>> BaseUnit : Size
    + Position : Point
    + Rotation : float
    + Scale : SizeF
    + Offset : Point
    + PositionAndScale : Point <<get>>
}
class Cell {
    - {static} <<readonly>> dmgFont : Font
    + type : CellType <<get>> <<set>>
    + id : string <<get>> <<set>>
    + kind : EnemyKind? <<get>> <<set>> = null
    + currency : int <<get>> <<set>>
    - state : State
    - dmgAround : int = 0
    - dmgAroundRelative : int = 0
    + Reload() : void
    + SetData(level:LevelData, columnId:int, rowId:int, fillColumns:int, fillRows:int) : void
    + SetEnemy(enemy:Enemy) : void
    + AddDmgAround(dmg:int) : void
    + UpdateDmgAround(dmg:int) : void
    + StartOpening() : void
    + FinishOpening() : void
    + Reset() : void
    + Update(deltaTime:float) : void
    + Draw() : void
    + DrawAfter() : void
}
IDynamicNode <|-- Cell
Cell --> "transform" Transform
Cell --> "level" LevelData
Cell o-> "peelingAnimation" PeelingCellAnimation
Cell o-> "enemy" Enemy
Cell --> "renderer" Renderer
class EnemyDeadEvent {
}
class Enemy {
    - {static} <<readonly>> dmgFont : Font
    - <<readonly>> tile : Image
    + Damage : int <<get>>
    - state : State
    + Enemy(x:int, y:int, kind:EnemyKind, bus:EventBus)
    + Defeat() : void
    + IsAlive() : bool
    + Reset() : void
    + Clone(x:int, y:int) : Enemy
    + Draw() : void
}
Event <|-- EnemyDeadEvent
EnemyDeadEvent o-> "Enemy" Enemy
IStaticNode <|-- Enemy
Enemy --> "Transform" Transform
Enemy --> "Collisioner" Collisioner
Enemy --> "renderer" Renderer
Enemy --> "bus" EventBus
class EnemyFactory {
    - <<readonly>> EnemyPrototypes : Dictionary<EnemyKind, Enemy>
    + EnemyFactory(bus:EventBus)
    + Create(x:int, y:int, kind:EnemyKind) : Enemy
    - RecreatePrototypes(bus:EventBus) : void
}
class GameManager {
    - state : GameState
    - <<readonly>> fontCollection : PrivateFontCollection
    - <<readonly>> font : Font
    - level : int
    - maxLvls : int
    - GameManager()
    - LoadCustomFont() : void
    + GetCustomFont(size:float) : Font
    - ReadLevelCount() : void
    + OnPlay() : void
    + OnRetry() : void
    + OnExit() : void
    - HandleLose(data:PlayerDiedEvent) : void
    + HandleVictory(data:LevelWinEvent) : void
    + NextLevel() : void
    + OnMainMenu() : void
    + Input() : void
    + Update(deltaTime:float) : void
    + Draw() : void
}
IDynamicNode <|-- GameManager
GameManager o-> "Instance" GameManager
GameManager --> "levelManager" LevelManager
GameManager --> "defeat" DefeatScreen
GameManager --> "victory" VictoryScreen
GameManager o-> "bus" EventBus
GameManager --> "levelUi" LevelUI
class Grid {
    + <<readonly>> MAX_ROW : int
    + <<readonly>> MAX_COLUMN : int
    - lvlRows : int
    - lvlColumns : int
    - fillRows : int
    - fillColumns : int
    - <<readonly>> emptyCells : List<Renderer>
    + Grid(bus:EventBus)
    - PlayerResetHandler(data:PlayerResetEvent) : void
    - PlayerMoveHandler(data:PlayerMoveEvent) : void
    - EnemyDeadHandler(data:EnemyDeadEvent) : void
    + GenerateLevel(level:LevelData, enemies:List<Enemy>, player:Player) : void
    - GenerateEmptyCells() : void
    + Reset() : void
    + PlayerCanMove(position:Point) : bool
    + CheckIfPlayerWon(player:Player) : void
    + Update(deltaTime:float) : void
    + Draw() : void
    + DrawAfter() : void
}
IDynamicNode <|-- Grid
Grid --> "enemyFactory" EnemyFactory
Grid --> "bus" EventBus
Grid --> "level" LevelData
class LevelData {
    + props : LevelDataProps <<get>> <<set>>
    + grid : List<List<Cell>> <<get>> <<set>>
    + Reset() : void
    + Reload() : void
    + AddDmgToCellsAround(dmg:int, columnId:int, rowId:int) : void
    + UpdateDmgToCellsAround(dmg:int, columnId:int, rowId:int) : void
    + AnimateOnReset(position:Point) : void
    + AnimateOnPlayerMove(position:Point) : void
}
class LevelWinEvent {
}
class ChangeLevelEvent {
    + <<readonly>> Level : int
}
class LevelManager {
    - <<readonly>> levels : Dictionary<int, LevelData>
    - {static} <<readonly>> enemies : List<Enemy>
    + {static} ActiveEnemies : List<Enemy> <<get>>
    + LevelManager(bus:EventBus)
    - LoadLevel(level:int) : LevelData
    + ResetLevel() : void
    - PlayerWillMoveHandler(data:PlayerWantToMoveEvent) : void
    - RunCollisions() : void
    + StartLevel(level:int) : void
    + <<override>> Input() : void
    + <<override>> Update(deltaTime:float) : void
    + <<override>> Draw() : void
}
Event <|-- LevelWinEvent
Event <|-- ChangeLevelEvent
InteractiveNode <|-- LevelManager
LevelManager --> "Renderer" Renderer
LevelManager --> "player" Player
LevelManager --> "grid" Grid
LevelManager --> "bus" EventBus
class PlayerMoveEvent {
    + <<readonly>> Position : Point
}
class PlayerWantToMoveEvent {
    + <<readonly>> Position : Point
}
class PlayerDmgEvent {
    + <<readonly>> Hp : int
    + <<readonly>> Dmg : int
}
class PlayerResetEvent {
    + <<readonly>> Hp : int
    + <<readonly>> Position : Point
}
class PlayerDiedEvent {
}
class Player {
    - start : Point
    + Tile : Image <<get>>
    - <<readonly>> maxHealth : int = 8
    + Hp : int <<get>>
    + Player(bus:EventBus, x:int, y:int)
    + SetStart(x:int, y:int) : void
    + Reset() : void
    + TakeDamage(damage:int) : void
    - IsDead() : bool
    + Move(newPosition:Point) : void
    + TryCollide(enemy:Enemy) : bool
    + <<override>> Input() : void
    + <<override>> Draw() : void
}
Event <|-- PlayerMoveEvent
Event <|-- PlayerWantToMoveEvent
Event <|-- PlayerDmgEvent
Event <|-- PlayerResetEvent
Event <|-- PlayerDiedEvent
InteractiveNode <|-- Player
Player --> "Collisioner" Collisioner
Player --> "Transform" Transform
Player --> "renderer" Renderer
Player --> "bus" EventBus
class Program <<static>> {
    + {static} deltaTime : float
    - {static} lastFrameTime : DateTime
    + {static} SCREEN_WIDTH : int = 1024
    + {static} SCREEN_HEIGHT : int = 720
    - {static} Main() : void
    - {static} CalcDeltatime() : void
    - {static} Input() : void
    - {static} Update() : void
    - {static} Render() : void
}
Program o-> "gameManager" GameManager
class DrawImageCommand {
    + texture : Image
    + Draw(e:PaintEventArgs) : void
}
IDrawCommand <|-- DrawImageCommand
DrawImageCommand o-> "transform" Transform
class DrawRectCommand {
    + rect : Rectangle
    + pen : Pen
    + brush : Brush
    + Draw(e:PaintEventArgs) : void
}
IDrawCommand <|-- DrawRectCommand
class DrawTextCommand {
    + text : string
    + font : Font
    + brush : Brush
    + position : Point
    + Draw(e:PaintEventArgs) : void
}
IDrawCommand <|-- DrawTextCommand
interface IDrawCommand {
    + Draw(e:PaintEventArgs) : void
}
abstract class Event {
    + Timestamp : DateTime <<get>>
}
class EventBus {
    - <<readonly>> subscribers : Dictionary<Type, List<object>>
    + Subscribe(handler:Action<T>) : void
    + Unsubscribe(handler:Action<T>) : void
    + Publish(eventData:T) : void
}
abstract class CanvaElement {
    + <<virtual>> Input() : void
    + {abstract} Draw() : void
}
interface IDynamicNode {
    + Update(deltaTime:float) : void
    + Draw() : void
}
abstract class InteractiveNode {
    + {abstract} Input() : void
    + <<virtual>> Update(deltaTime:float) : void
    + {abstract} Draw() : void
}
interface IStaticNode {
    + Draw() : void
}
class PeelingCellAnimation {
    +  <<event>> OnFinish : PeelingEnd 
    - progress : float
    - <<readonly>> sec : float = 0.8f
    + SetData(transform:Transform, point:Point) : void
    + Reset() : void
    + Update(deltaTime:float) : void
    + Draw(e:PaintEventArgs) : void
}
IDrawCommand <|-- PeelingCellAnimation
PeelingCellAnimation --> "transform" Transform
PeelingCellAnimation --> "BaseImageCmd" DrawImageCommand
class DefeatScreen {
    - result : DefeatResult
    - <<readonly>> font : Font
    + EnableDefeat() : void
    + <<override>> Input() : void
    + <<override>> Draw() : void
}
CanvaElement <|-- DefeatScreen
DefeatScreen o-> "renderer" Renderer
class HpBar {
    - BaseHp : int = 0
    - Hp : int = 0
    - {static} Scale : Size
    + HpBar(bus:EventBus)
    - HandlePlayerDmg(data:PlayerDmgEvent) : void
    - HandlePlayerReset(data:PlayerResetEvent) : void
    + <<override>> Draw() : void
}
CanvaElement <|-- HpBar
HpBar o-> "HpFrameRenderer" Renderer
HpBar o-> "HpBaseRenderer" Renderer
HpBar --> "HpRenderer" Renderer
HpBar --> "HpTransform" Transform
class LevelUI {
    + <<override>> Draw() : void
}
CanvaElement <|-- LevelUI
LevelUI o-> "playerInfo" PlayerInfo
LevelUI o-> "stageBar" StageBar
class MainMenu {
    - <<readonly>> font : Font
    - result : MenuResult
    + <<override>> Input() : void
    + <<override>> Draw() : void
}
CanvaElement <|-- MainMenu
MainMenu o-> "renderer" Renderer
class PlayerInfo {
    + <<override>> Draw() : void
}
CanvaElement <|-- PlayerInfo
PlayerInfo o-> "hpBar" HpBar
class StageBar {
    - level : int = 0
    - <<readonly>> font : Font
    + StageBar(font:Font, bus:EventBus)
    - HandleLevelChange(data:ChangeLevelEvent) : void
    + <<override>> Draw() : void
}
CanvaElement <|-- StageBar
StageBar --> "textBoxRenderer" Renderer
StageBar --> "transform" Transform
class VictoryScreen {
    - <<readonly>> font : Font
    - option : Option
    - isCompleted : bool = false
    + EnableVictory(isCompleted:bool) : void
    + <<override>> Input() : void
    + <<override>> Draw() : void
}
CanvaElement <|-- VictoryScreen
VictoryScreen o-> "renderer" Renderer
VictoryScreen o-> "WinRenderer" Renderer
VictoryScreen o-> "WinBackgroundRenderer" Renderer
