@startuml
class Collisioner {
    + UpdatePosition(transform:Transform) : void
    + CheckCollision(element:Collisioner) : bool
}
Collisioner o-> "rect" Rectangle
class ColorJsonConverter {
    + <<override>> Read(reader:Utf8JsonReader, typeToConvert:System.Type, options:JsonSerializerOptions) : Color
    + <<override>> Write(writer:Utf8JsonWriter, value:Color, options:JsonSerializerOptions) : void
}
class "JsonConverter`1"<T> {
}
"JsonConverter`1" "<Color>" <|-- ColorJsonConverter
class Engine <<static>> {
    + {static} IsWindowOpen : bool <<get>>
    + {static} Initialize(title:string, width:int, height:int, fullscreen:bool) : void
    + {static} UpdateWindow() : void
    + {static} PlaySound(path:string) : void
    + {static} DrawACommand(command:IDrawCommand) : void
    + {static} DrawRect(rect:Rectangle, pen:Pen, brush:Brush) : void
    + {static} DrawText(text:string, font:Font, brush:Brush, position:Point) : void
    + {static} Clear(color:Color) : void
    + {static} OnKeyDown(key:Keys) : bool
    + {static} OnKeyUp(key:Keys) : bool
    + {static} IsKeyDown(key:Keys) : bool
    + {static} IsKeyPressed(key:Keys) : bool
    + {static} DebugLog(message:string) : void
    + {static} ClearDebug() : void
}
class "Dictionary`2"<T1,T2> {
}
class "List`1"<T> {
}
class "HashSet`1"<T> {
}
class GameForm {
    + GameForm()
    # <<override>> OnPaint(e:PaintEventArgs) : void
}
Engine o-> "sounds<string,SoundPlayer>" "Dictionary`2"
Engine o-> "drawQueue<IDrawCommand>" "List`1"
Engine --> "window" GameForm
Engine --> "Window" Form
Engine o-> "pressedKeys<Keys>" "HashSet`1"
Engine o-> "handledKeys<Keys>" "HashSet`1"
Engine o-> "releasedKeys<Keys>" "HashSet`1"
Engine o-> "handledReleasedKeys<Keys>" "HashSet`1"
Engine o-> "debugMessages<string>" "List`1"
Engine o-> "debugFont" Font
Engine o-> "debugBrush" Brush
Engine +-- GameForm
Form <|-- GameForm
GameForm o-> "ClearColor" Color
class PointJsonConverter {
    + <<override>> Read(reader:Utf8JsonReader, typeToConvert:System.Type, options:JsonSerializerOptions) : Point
    + <<override>> Write(writer:Utf8JsonWriter, value:Point, options:JsonSerializerOptions) : void
}
class "JsonConverter`1"<T> {
}
"JsonConverter`1" "<Point>" <|-- PointJsonConverter
class Renderer {
    + Draw() : void
}
Renderer o-> "Command" IDrawCommand
class TileMap {
    + {static} Size : int <<get>> = 32
    + {static} LoadSprite(path:string, row:int, column:int) : Bitmap
}
class Transform {
    + Rotation : float
}
Transform o-> "Position" Point
Transform o-> "BaseUnit" Size
Transform o-> "Scale" Size
Transform --> "PositionAndScale" Point
enum CellType {
    NULL,
    ENEMY,
    COIN,
    START,
    END,
}
class Cell {
    + id : string <<get>> <<set>>
    + currency : int <<get>> <<set>>
    + SetData(level:LevelData, columnId:int, rowId:int, fillColumns:int, fillRows:int) : void
    + StartOpening() : void
    + FinishOpening(sender:object, e:EventArgs) : void
    + Reset() : void
    + Update(deltaTime:float) : void
    + Draw() : void
    + DrawAfter() : void
}
enum State {
    INIT= 'I',
    OPENING= 'O',
    OPEN= 'N',
}
IDynamicNode <|-- Cell
Cell o-> "type" CellType
Cell o-> "kind" EnemyKind
Cell --> "rect" Rectangle
Cell --> "transform" Transform
Cell o-> "state" State
Cell --> "level" LevelData
Cell o-> "animation" PeelingCellAnimation
Cell +-- State
enum EnemyKind {
    GOBLIN_ROGUE,
    GOBLIN_ARCHER,
    GOBLIN_MAGE,
    GOBLINBARBARIC,
    GOBLIN_BOSS_1,
    GOBLIN_BOSS_2,
    GOBLIN_BOSS_3,
}
class Enemy {
    + Damage : int <<get>>
    + Enemy(x:int, y:int, kind:EnemyKind)
    + Defeat() : void
    + IsAlive() : bool
    + Reset() : void
    + Clone(x:int, y:int) : Enemy
    + Draw() : void
}
enum State {
    ALIVE,
    DEAD,
}
class DataManager <<static>> {
}
class EnemyData {
    + damage : int <<get>> <<set>>
}
class "Dictionary`2"<T1,T2> {
}
IStaticNode <|-- Enemy
Enemy --> "Transform" Transform
Enemy --> "tile" Image
Enemy o-> "state" State
Enemy --> "Collisioner" Collisioner
Enemy --> "Renderer" Renderer
Enemy +-- State
Enemy +-- DataManager
DataManager o-> "enemyData<EnemyKind,EnemyData>" "Dictionary`2"
Enemy +-- EnemyData
EnemyData --> "point" Point
class EnemyFactory {
    - EnemyFactory()
    + {static} Create(x:int, y:int, kind:EnemyKind) : Enemy
    - RecreatePrototypes() : void
}
class "Dictionary`2"<T1,T2> {
}
EnemyFactory o-> "EnemyPrototypes<EnemyKind,Enemy>" "Dictionary`2"
EnemyFactory o-> "Instance" EnemyFactory
class GameManager {
    - level : int
    - maxLvls : int
    - GameManager()
    - ReadLevelCount() : void
    + OnPlay() : void
    + OnRetry() : void
    + OnExit() : void
    - HandleLose() : void
    + OnVictory() : void
    + NextLevel() : void
    + OnMainMenu() : void
    + Input() : void
    + Update(deltaTime:float) : void
    + Draw() : void
}
enum GameState {
    MAIN_MENU,
    PLAYING_LEVEL,
    VICTORY,
    DEFEAT,
    QUIT,
}
IDynamicNode <|-- GameManager
GameManager o-> "state" GameState
GameManager o-> "Instance" GameManager
GameManager o-> "font" Font
GameManager o-> "levelManager" LevelManager
GameManager --> "defeat" DefeatScreen
GameManager --> "victory" VictoryScreen
GameManager +-- GameState
class Grid {
    - <<readonly>> MAX_ROW : int = 16
    - <<readonly>> MAX_COLUMN : int = 32
    - lvlRow : int
    - lvlColumn : int
    - fillRows : int
    - fillColumns : int
    + SetLevel(level:LevelData) : void
    + Reset() : void
    + Update(deltaTime:float) : void
    + Draw() : void
    + DrawAfter() : void
}
IDynamicNode <|-- Grid
Grid --> "level" LevelData
class LevelDataProps {
}
class LevelData {
}
class LevelManager {
    +  <<event>> OnLose : LevelEventLose 
    - <<readonly>> MAX_ROW : int = 16
    - <<readonly>> MAX_COLUMN : int = 32
    - lvlRows : int
    - lvlColumns : int
    - fillRows : int
    - fillColumns : int
    - LevelManager()
    + LoadLevel(level:int) : void
    - CreateLevel() : void
    + ResetLevel() : void
    - PlayerDeathHandler() : void
    - PlayerWillMoveHandler(position:Point) : void
    - RunCollisions() : void
    - CheckVictoryCondition() : void
    + StartLevel(level:int) : void
    + Init(font:Font) : void
    + Input() : void
    + Update(deltaTime:float) : void
    + Draw() : void
}
class "List`1"<T> {
}
class "Dictionary`2"<T1,T2> {
}
LevelDataProps --> "start" Color
LevelDataProps --> "end" Color
LevelDataProps --> "basic" Color
LevelDataProps --> "lineMesh" Color
LevelDataProps --> "treasure" Color
LevelDataProps --> "background" Color
LevelData --> "props" LevelDataProps
LevelData --> "grid<List<Cell>>" "List`1"
IInteractiveNode <|-- LevelManager
LevelManager o-> "levels<int,LevelData>" "Dictionary`2"
LevelManager --> "currentLevel" LevelData
LevelManager --> "Renderer" Renderer
LevelManager o-> "player" Player
LevelManager o-> "enemies<Enemy>" "List`1"
LevelManager --> "ActiveEnemies<Enemy>" "List`1"
LevelManager o-> "grid" Grid
LevelManager --> "ui" LevelUI
LevelManager o-> "Instance" LevelManager
class Player {
    +  <<event>> OnWillMove : PlayerEventWillMove 
    +  <<event>> OnDeath : PlayerEventIsDead 
    - <<readonly>> maxHealth : int = 8
    + Hp : int <<get>>
    + Player(x:int, y:int)
    + SetStart(x:int, y:int) : void
    + Reset() : void
    + TakeDamage(damage:int) : void
    - IsDead() : bool
    + Move(newPosition:Point) : void
    + TryCollide(enemy:Enemy) : bool
    + Input() : void
    + Update(deltaTime:float) : void
    + Draw() : void
}
IInteractiveNode <|-- Player
Player --> "start" Point
Player --> "Tile" Image
Player --> "Collisioner" Collisioner
Player --> "Transform" Transform
Player --> "Renderer" Renderer
class Program <<static>> {
    + {static} deltaTime : float
    + {static} showDebug : bool = true
    + {static} currentMsg : string = ""
    + {static} SCREEN_WIDTH : int = 1024
    + {static} SCREEN_HEIGHT : int = 720
    - {static} Main() : void
    - {static} CalcDeltatime() : void
    - {static} Input() : void
    - {static} Update() : void
    - {static} Render() : void
}
Program o-> "lastFrameTime" DateTime
Program o-> "gameManager" GameManager
class DrawImageCommand {
    + Draw(e:PaintEventArgs) : void
}
IDrawCommand <|-- DrawImageCommand
DrawImageCommand o-> "texture" Image
DrawImageCommand o-> "transform" Transform
class DrawRectCommand {
    + Draw(e:PaintEventArgs) : void
}
IDrawCommand <|-- DrawRectCommand
DrawRectCommand --> "rect" Rectangle
DrawRectCommand --> "pen" Pen
DrawRectCommand --> "brush" Brush
class DrawTextCommand {
    + text : string
    + Draw(e:PaintEventArgs) : void
}
IDrawCommand <|-- DrawTextCommand
DrawTextCommand --> "font" Font
DrawTextCommand --> "brush" Brush
DrawTextCommand --> "position" Point
interface IDrawCommand {
    + Draw(e:PaintEventArgs) : void
}
interface ICanvaElement {
    + Input() : void
    + Draw() : void
}
interface IDynamicNode {
    + Update(deltaTime:float) : void
    + Draw() : void
}
interface IInteractiveNode {
    + Input() : void
    + Update(deltaTime:float) : void
    + Draw() : void
}
interface IStaticNode {
    + Draw() : void
}
class PeelingCellAnimation {
    +  <<event>> OnFinish : EventHandler 
    - progress : float
    - <<readonly>> sec : float = 1.5f
    + SetData(transform:Transform) : void
    + Reset() : void
    + Update(deltaTime:float) : void
    + Draw(e:PaintEventArgs) : void
}
IDrawCommand <|-- PeelingCellAnimation
PeelingCellAnimation --> "transform" Transform
class DefeatScreen {
    + EnableDefeat() : void
    + Input() : void
    + Draw() : void
}
enum DefeatResult {
    Retry,
    MainMenu,
}
ICanvaElement <|-- DefeatScreen
DefeatScreen o-> "Renderer" Renderer
DefeatScreen o-> "result" DefeatResult
DefeatScreen o-> "font" Font
DefeatScreen +-- DefeatResult
class LevelUI {
    - level : int
    + SetLevel(level:int) : void
    + Input() : void
    + Draw() : void
}
ICanvaElement <|-- LevelUI
LevelUI o-> "playerInfo" PlayerInfo
LevelUI o-> "font" Font
class MainMenu {
    + Input() : void
    + Draw() : void
}
enum MenuResult {
    Play,
    Exit,
}
ICanvaElement <|-- MainMenu
MainMenu o-> "font" Font
MainMenu o-> "Renderer" Renderer
MainMenu o-> "result" MenuResult
MainMenu +-- MenuResult
class PlayerInfo {
    + Input() : void
    + Draw() : void
}
ICanvaElement <|-- PlayerInfo
PlayerInfo o-> "player" Player
PlayerInfo o-> "font" Font
PlayerInfo o-> "Renderer" Renderer
class VictoryScreen {
    + Input() : void
    + Draw() : void
}
enum Option {
    Next,
    MainMenu,
}
ICanvaElement <|-- VictoryScreen
VictoryScreen o-> "backgroundImg" Image
VictoryScreen o-> "font" Font
VictoryScreen o-> "option" Option
VictoryScreen o-> "Renderer" Renderer
VictoryScreen +-- Option
@enduml
