@startuml
class Engine <<static>> {
    + {static} IsWindowOpen : bool <<get>>
    + {static} Initialize(title:string, width:int, height:int, fullscreen:bool) : void
    + {static} UpdateWindow() : void
    + {static} PlaySound(path:string) : void
    + {static} DrawACommand(command:IDrawCommand) : void
    + {static} DrawRect(rect:Rectangle, pen:Pen, brush:Brush) : void
    + {static} DrawText(text:string, font:Font, brush:Brush, position:Point) : void
    + {static} Clear(color:Color) : void
    + {static} OnKeyDown(key:Keys) : bool
    + {static} OnKeyUp(key:Keys) : bool
    + {static} IsKeyDown(key:Keys) : bool
    + {static} IsKeyPressed(key:Keys) : bool
    + {static} DebugLog(message:string) : void
    + {static} ClearDebug() : void
}
class "Dictionary`2"<T1,T2> {
}
class "List`1"<T> {
}
class "HashSet`1"<T> {
}
class GameForm {
    + GameForm()
    # <<override>> OnPaint(e:PaintEventArgs) : void
}
Engine o-> "sounds<string,SoundPlayer>" "Dictionary`2"
Engine o-> "drawQueue<IDrawCommand>" "List`1"
Engine --> "window" GameForm
Engine --> "Window" Form
Engine o-> "pressedKeys<Keys>" "HashSet`1"
Engine o-> "handledKeys<Keys>" "HashSet`1"
Engine o-> "releasedKeys<Keys>" "HashSet`1"
Engine o-> "handledReleasedKeys<Keys>" "HashSet`1"
Engine o-> "debugMessages<string>" "List`1"
Engine o-> "debugFont" Font
Engine o-> "debugBrush" Brush
Engine +-- GameForm
Form <|-- GameForm
GameForm o-> "ClearColor" Color
@enduml
