class Engine <<static>> {
    - {static} <<readonly>> sounds : Dictionary<string, SoundPlayer>
    - {static} <<readonly>> drawQueue : List<IDrawCommand>
    - {static} window : GameForm
    + {static} IsWindowOpen : bool <<get>>
    + {static} Window : Form <<get>>
    - {static} <<readonly>> pressedKeys : HashSet<Keys>
    - {static} <<readonly>> handledKeys : HashSet<Keys>
    - {static} <<readonly>> releasedKeys : HashSet<Keys>
    - {static} <<readonly>> handledReleasedKeys : HashSet<Keys>
    - {static} <<readonly>> debugMessages : List<string>
    - {static} <<readonly>> debugFont : Font
    - {static} <<readonly>> debugBrush : Brush
    + {static} Initialize(title:string, width:int, height:int, fullscreen:bool) : void
    + {static} UpdateWindow() : void
    + {static} PlaySound(path:string) : void
    + {static} DrawACommand(command:IDrawCommand) : void
    + {static} DrawRect(rect:Rectangle, pen:Pen, brush:Brush) : void
    + {static} DrawText(text:string, font:Font, brush:Brush, position:Point) : void
    + {static} Clear(color:Color) : void
    + {static} OnKeyDown(key:Keys) : bool
    + {static} OnKeyUp(key:Keys) : bool
    + {static} IsKeyDown(key:Keys) : bool
    + {static} IsKeyPressed(key:Keys) : bool
    + {static} DebugLog(message:string) : void
    + {static} ClearDebug() : void
}
