@startuml
class DrawImageCommand {
    + X : float
    + Y : float
    + ScaleX : float
    + ScaleY : float
    + Angle : float
    + OffsetX : float
    + OffsetY : float
    + Draw(e:PaintEventArgs) : void
}
IDrawCommand <|-- DrawImageCommand
DrawImageCommand --> "texture" Image
@enduml
