@startuml
class DefeatScreen {
    + EnableDefeat() : void
    + Input() : void
    + Draw() : void
}
enum DefeatResult {
    Retry,
    MainMenu,
}
ICanvaElement <|-- DefeatScreen
DefeatScreen o-> "bgImg" Image
DefeatScreen o-> "result" DefeatResult
DefeatScreen o-> "font" Font
DefeatScreen +-- DefeatResult
@enduml
