class DefeatScreen {
    - result : DefeatResult
    - <<readonly>> font : Font
    + EnableDefeat() : void
    + <<override>> Input() : void
    + <<override>> Draw() : void
}
CanvaElement <|-- DefeatScreen
DefeatScreen o-> "renderer" Renderer
