@startuml
class LevelUI {
    - level : int
    + SetLevel(level:int) : void
    + Input() : void
    + Draw() : void
}
ICanvaElement <|-- LevelUI
LevelUI o-> "playerInfo" PlayerInfo
LevelUI o-> "font" Font
@enduml
