@startuml
class MainMenu {
    + Input() : void
    + Draw() : void
}
enum MenuResult {
    Play,
    Exit,
}
ICanvaElement <|-- MainMenu
MainMenu o-> "font" Font
MainMenu o-> "menuImg" Image
MainMenu o-> "result" MenuResult
MainMenu +-- MenuResult
@enduml
