class MainMenu {
    - <<readonly>> font : Font
    - result : MenuResult
    + <<override>> Input() : void
    + <<override>> Draw() : void
}
CanvaElement <|-- MainMenu
MainMenu o-> "renderer" Renderer
