@startuml
class PlayerInfo {
    + Input() : void
    + Draw() : void
}
ICanvaElement <|-- PlayerInfo
PlayerInfo o-> "player" Player
PlayerInfo o-> "font" Font
PlayerInfo o-> "Renderer" Renderer
@enduml
