class PlayerInfo {
    - Hp : int = 0
    - <<readonly>> font : Font
    + PlayerInfo(font:Font, bus:EventBus)
    - HandlePlayerDmg(data:PlayerDmgEvent) : void
    - HandlePlayerReset(data:PlayerResetEvent) : void
    + <<override>> Draw() : void
}
CanvaElement <|-- PlayerInfo
PlayerInfo o-> "renderer" Renderer
