class VictoryScreen {
    - <<readonly>> font : Font
    - option : Option
    + <<override>> Input() : void
    + <<override>> Draw() : void
}
CanvaElement <|-- VictoryScreen
VictoryScreen o-> "renderer" Renderer
