@startuml
class VictoryScreen {
    + Input() : void
    + Draw() : void
}
enum Option {
    Next,
    MainMenu,
}
ICanvaElement <|-- VictoryScreen
VictoryScreen o-> "backgroundImg" Image
VictoryScreen o-> "font" Font
VictoryScreen o-> "option" Option
VictoryScreen +-- Option
@enduml
