@startuml
class VictoryScreen {
    + <<override>> Input() : void
    + <<override>> Draw() : void
}
enum Option {
    Next,
    MainMenu,
}
Node <|-- VictoryScreen
VictoryScreen o-> "backgroundImg" Image
VictoryScreen o-> "font" Font
VictoryScreen o-> "option" Option
VictoryScreen +-- Option
@enduml
