@startuml
class Enemy {
    + Damage : int <<get>>
    + Enemy(x:int, y:int, kind:EnemyKind)
    + Defeat() : void
    + IsAlive() : bool
    + Reset() : void
    + <<override>> Draw() : void
}
enum EnemyKind {
    GOBLIN_ROGUE,
    GOBLIN_ARCHER,
    GOBLIN_MAGE,
    GOBLINBARBARIC,
    GOBLIN_BOSS_1,
    GOBLIN_BOSS_2,
    GOBLIN_BOSS_3,
}
enum State {
    ALIVE,
    DEAD,
}
class EnemyData {
    + damage : int <<get>> <<set>>
}
class "Dictionary`2"<T1,T2> {
}
Node <|-- Enemy
Enemy --> "position" Point
Enemy --> "actualPosition" Point
Enemy --> "tile" Image
Enemy o-> "enemyData<EnemyKind,EnemyData>" "Dictionary`2"
Enemy o-> "state" State
Enemy --> "Collisioner" Collisioner
Enemy +-- EnemyKind
Enemy +-- State
Enemy +-- EnemyData
EnemyData --> "point" Point
@enduml
