class PeelingCellAnimation {
    +  <<event>> OnFinish : EventHandler 
    - progress : float
    - <<readonly>> sec : float = 1.5f
    + SetData(transform:Transform) : void
    + Reset() : void
    + Update(deltaTime:float) : void
    + Draw(e:PaintEventArgs) : void
}
IDrawCommand <|-- PeelingCellAnimation
PeelingCellAnimation --> "transform" Transform
